language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - ci/check-basic-style.sh
  - ci/compile-all.sh
  - ci/test-all.sh

cache: cargo
